// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCiC-2Cbd_FEr5lyqHecXLMFrVT8ClXcE',
    appId: '1:994994923945:web:47ecd3a1999a5cb9a97cb8',
    messagingSenderId: '994994923945',
    projectId: 'workalot-9e092',
    authDomain: 'workalot-9e092.firebaseapp.com',
    storageBucket: 'workalot-9e092.firebasestorage.app',
    measurementId: 'G-S0R7D0JMTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf3Rm7OiDh-LV0EIZ76OTEbuaajf6dFiQ',
    appId: '1:994994923945:android:ce2f961deefb4852a97cb8',
    messagingSenderId: '994994923945',
    projectId: 'workalot-9e092',
    storageBucket: 'workalot-9e092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8axn3r8AAlDgzvz6YWaquV6cVcL12QcQ',
    appId: '1:994994923945:ios:632af814e3352417a97cb8',
    messagingSenderId: '994994923945',
    projectId: 'workalot-9e092',
    storageBucket: 'workalot-9e092.firebasestorage.app',
    iosBundleId: 'com.example.workalot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8axn3r8AAlDgzvz6YWaquV6cVcL12QcQ',
    appId: '1:994994923945:ios:632af814e3352417a97cb8',
    messagingSenderId: '994994923945',
    projectId: 'workalot-9e092',
    storageBucket: 'workalot-9e092.firebasestorage.app',
    iosBundleId: 'com.example.workalot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCiC-2Cbd_FEr5lyqHecXLMFrVT8ClXcE',
    appId: '1:994994923945:web:26ea1a1b514543dca97cb8',
    messagingSenderId: '994994923945',
    projectId: 'workalot-9e092',
    authDomain: 'workalot-9e092.firebaseapp.com',
    storageBucket: 'workalot-9e092.firebasestorage.app',
    measurementId: 'G-0XNKB298FN',
  );
}
